// <auto-generated />
using System;
using AiMusicWorkstation.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiMusicWorkstation.Infrastructure.Migrations
{
    [DbContext(typeof(AiMusicWorkstationDbContext))]
    [Migration("20260904130954_AddChords")]
    partial class AddChords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiMusicWorkstation.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("AiMusicWorkstation.Domain.Entities.SongGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("song_groups", (string)null);
                });

            modelBuilder.Entity("AiMusicWorkstation.Domain.Entities.SongProject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("artist");

                    b.Property<double>("Bpm")
                        .HasColumnType("double precision")
                        .HasColumnName("bpm");

                    b.Property<int>("BpmSource")
                        .HasColumnType("integer")
                        .HasColumnName("BpmSource");

                    b.Property<string>("Chords")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chords");

                    b.Property<int>("ChordsSource")
                        .HasColumnType("integer")
                        .HasColumnName("ChordsSource");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_added");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("genre");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("group_name");

                    b.Property<bool>("IsOfficialData")
                        .HasColumnType("boolean")
                        .HasColumnName("is_official_data");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<int>("KeySource")
                        .HasColumnType("integer")
                        .HasColumnName("KeySource");

                    b.Property<string>("Lyrics")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lyrics");

                    b.Property<int>("LyricsSource")
                        .HasColumnType("integer")
                        .HasColumnName("LyricsSource");

                    b.Property<string>("OriginalPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_path");

                    b.Property<string>("Sections")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sections");

                    b.Property<int>("SectionsSource")
                        .HasColumnType("integer")
                        .HasColumnName("StructureSource");

                    b.Property<string>("SpotifyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spotify_id");

                    b.Property<string>("StemsPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stems_path");

                    b.Property<int>("TimeSigSource")
                        .HasColumnType("integer")
                        .HasColumnName("TimeSignatureSource");

                    b.Property<int>("TimeSignature")
                        .HasColumnType("integer")
                        .HasColumnName("time_signature");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("songs", (string)null);
                });

            modelBuilder.Entity("AiMusicWorkstation.Domain.Entities.SongProject", b =>
                {
                    b.HasOne("AiMusicWorkstation.Domain.Entities.SongGroup", "Group")
                        .WithMany("Songs")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("AiMusicWorkstation.Domain.Entities.SongGroup", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
